# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_report_backtest_img'),
        ('file', '0002_remove_filerecord_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.Report'),
            preserve_default=False,
        ),
    ]
