# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='backtest_img',
            field=models.ForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, to='file.FileRecord'),
        ),
    ]
