# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180904_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='backtest_img',
        ),
    ]
